# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Todos Conta 1
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Todos juntos para derrotar o mosquito
baseurl: "/TodosContra1" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Social media profiles - feel free to add more here
twitter_username: devryruybarbosa
instagram_username:  facdevryruybarbosa
facebook_username: faculdadedevryruybarbosa

# Address information
address_street:
address_city: Brasil

# Build settings
markdown: kramdown
